[2024-01-10T14:11:35.711+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_2.group_a.tsk_create_table_1 manual__2024-01-10T14:04:59.133430+00:00 [queued]>
[2024-01-10T14:11:35.717+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_2.group_a.tsk_create_table_1 manual__2024-01-10T14:04:59.133430+00:00 [queued]>
[2024-01-10T14:11:35.718+0000] {taskinstance.py:2171} INFO - Starting attempt 3 of 3
[2024-01-10T14:11:35.726+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): group_a.tsk_create_table_1> on 2024-01-10 14:04:59.133430+00:00
[2024-01-10T14:11:35.730+0000] {standard_task_runner.py:60} INFO - Started process 3308 to run task
[2024-01-10T14:11:35.733+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag_2', 'group_a.tsk_create_table_1', 'manual__2024-01-10T14:04:59.133430+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpffnkjxmc']
[2024-01-10T14:11:35.736+0000] {standard_task_runner.py:88} INFO - Job 53: Subtask group_a.tsk_create_table_1
[2024-01-10T14:11:35.773+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag_2.group_a.tsk_create_table_1 manual__2024-01-10T14:04:59.133430+00:00 [running]> on host 2eb95800a276
[2024-01-10T14:11:35.822+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag_2' AIRFLOW_CTX_TASK_ID='group_a.tsk_create_table_1' AIRFLOW_CTX_EXECUTION_DATE='2024-01-10T14:04:59.133430+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-10T14:04:59.133430+00:00'
[2024-01-10T14:11:35.824+0000] {sql.py:276} INFO - Executing:   
                    CREATE TABLE IF NOT EXISTS city_look_up (
                    city TEXT NOT NULL,
                    state TEXT NOT NULL,
                    census_2020 numeric NOT NULL,
                    land_Area_sq_mile_2020 numeric NOT NULL                    
                );
                
[2024-01-10T14:11:35.830+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-01-10T14:11:35.839+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-01-10T14:12:50.847+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "***.ch88u8kcg7dc.us-east-1.rds.amazonaws.com" (3.230.25.99), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-01-10T14:12:50.867+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=weather_dag_2, task_id=group_a.tsk_create_table_1, execution_date=20240110T140459, start_date=20240110T141135, end_date=20240110T141250
[2024-01-10T14:12:50.884+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 53 for task group_a.tsk_create_table_1 (connection to server at "***.ch88u8kcg7dc.us-east-1.rds.amazonaws.com" (3.230.25.99), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 3308)
[2024-01-10T14:12:50.935+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-10T14:12:50.958+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
