[2024-01-10T13:34:30.970+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: weather_dag_2.group_a.tsk_create_table_1 manual__2024-01-10T13:31:11.375654+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
