[2024-01-10T14:19:12.018+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_2.group_a.tsk_uploadS3_to_postgres manual__2024-01-10T14:18:53.812943+00:00 [queued]>
[2024-01-10T14:19:12.024+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_2.group_a.tsk_uploadS3_to_postgres manual__2024-01-10T14:18:53.812943+00:00 [queued]>
[2024-01-10T14:19:12.024+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-01-10T14:19:12.033+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): group_a.tsk_uploadS3_to_postgres> on 2024-01-10 14:18:53.812943+00:00
[2024-01-10T14:19:12.037+0000] {standard_task_runner.py:60} INFO - Started process 3432 to run task
[2024-01-10T14:19:12.040+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag_2', 'group_a.tsk_uploadS3_to_postgres', 'manual__2024-01-10T14:18:53.812943+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp2asrr4zj']
[2024-01-10T14:19:12.043+0000] {standard_task_runner.py:88} INFO - Job 57: Subtask group_a.tsk_uploadS3_to_postgres
[2024-01-10T14:19:12.078+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag_2.group_a.tsk_uploadS3_to_postgres manual__2024-01-10T14:18:53.812943+00:00 [running]> on host 2eb95800a276
[2024-01-10T14:19:12.126+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag_2' AIRFLOW_CTX_TASK_ID='group_a.tsk_uploadS3_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-01-10T14:18:53.812943+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-10T14:18:53.812943+00:00'
[2024-01-10T14:19:12.127+0000] {sql.py:276} INFO - Executing: SELECT aws_s3.table_import_from_s3('city_look_up', '', '(format csv, DELIMITER '','', HEADER true)', 's3-bucket-weather-api', 'us_city.csv', 'us-east-1');
[2024-01-10T14:19:12.133+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-01-10T14:19:12.142+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-01-10T14:19:15.668+0000] {sql.py:432} INFO - Running statement: SELECT aws_s3.table_import_from_s3('city_look_up', '', '(format csv, DELIMITER '','', HEADER true)', 's3-bucket-weather-api', 'us_city.csv', 'us-east-1');, parameters: None
[2024-01-10T14:19:17.944+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 437, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InternalError_: HTTP 404. Requested file does not exist.

[2024-01-10T14:19:17.951+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag_2, task_id=group_a.tsk_uploadS3_to_postgres, execution_date=20240110T141853, start_date=20240110T141912, end_date=20240110T141917
[2024-01-10T14:19:17.960+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 57 for task group_a.tsk_uploadS3_to_postgres (HTTP 404. Requested file does not exist.
; 3432)
[2024-01-10T14:19:18.004+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-10T14:19:18.018+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
